spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cova_task_manager}
    username: ${DB_USERNAME:cova}
    password: ${DB_PASSWORD:cova}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
